; RustCarPlay's Chinese wizard messages. Uncommon system errors inherit the
; compiler's current English messages so new Inno versions remain compatible.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI
DialogFontSize=9

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
SetupLdrStartupMessage=即将安装 %1。是否继续？
SetupFileMissing=安装文件 %1 缺失。请重新下载安装包。
SetupFileCorrupt=安装文件已损坏。请重新下载安装包。
SetupAlreadyRunning=安装程序已经在运行。
WindowsVersionNotSupported=此程序不支持当前 Windows 版本。
SetupAppRunningError=安装程序检测到 %1 正在运行。%n%n请关闭程序后点击“确定”继续。
UninstallAppRunningError=卸载程序检测到 %1 正在运行。%n%n请关闭程序后点击“确定”继续。
ErrorCreatingDir=无法创建目录“%1”
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将不会完成安装。%n%n是否退出？
AboutSetupMenuItem=关于安装程序(&A)...
AboutSetupTitle=关于安装程序
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全部是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全部否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=请选择安装过程中使用的语言。
ClickNext=点击“下一步”继续，或点击“取消”退出。
BrowseDialogTitle=选择文件夹
BrowseDialogLabel=选择文件夹，然后点击“确定”。
NewFolderName=新建文件夹
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=此向导将在您的电脑上安装 [name/ver]。%n%n请先关闭正在运行的 RustCarPlay。
WizardLicense=许可协议
LicenseLabel=继续之前，请阅读以下信息。
LicenseLabel3=请阅读许可协议。继续安装前，您需要接受协议条款。
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
WizardInfoBefore=安装说明
InfoBeforeLabel=继续之前，请阅读以下信息。
InfoBeforeClickLabel=准备好后，点击“下一步”。
WizardInfoAfter=安装说明
InfoAfterLabel=请阅读以下信息。
InfoAfterClickLabel=准备好后，点击“下一步”。
WizardSelectDir=选择安装位置
SelectDirDesc=您希望将 [name] 安装在哪里？
SelectDirLabel3=程序将安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续，或点击“浏览”更改位置。
DiskSpaceGBLabel=至少需要 [gb] GB 可用磁盘空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用磁盘空间。
DiskSpaceWarningTitle=磁盘空间不足
DiskSpaceWarning=安装至少需要 %1 KB 可用空间，但当前磁盘仅有 %2 KB。%n%n是否继续？
DirNameTooLong=文件夹名称或路径过长。
InvalidDirName=文件夹名称无效。
DirExistsTitle=文件夹已存在
DirExists=文件夹：%n%n%1%n%n已经存在。是否安装到此文件夹？
DirDoesntExistTitle=文件夹不存在
DirDoesntExist=文件夹：%n%n%1%n%n不存在。是否创建？
WizardSelectTasks=选择附加任务
SelectTasksDesc=需要执行哪些附加任务？
SelectTasksLabel2=选择需要执行的任务，然后点击“下一步”。
WizardSelectProgramGroup=选择开始菜单文件夹
SelectStartMenuFolderDesc=快捷方式放在哪里？
SelectStartMenuFolderLabel3=程序将在以下开始菜单文件夹中创建快捷方式。
SelectStartMenuFolderBrowseLabel=点击“下一步”继续，或点击“浏览”更改位置。
NoProgramGroupCheck2=不创建开始菜单文件夹(&D)
WizardReady=准备安装
ReadyLabel1=已准备好将 [name] 安装到您的电脑。
ReadyLabel2a=点击“安装”开始，或点击“上一步”检查和修改设置。
ReadyLabel2b=点击“安装”开始。
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单文件夹：
ReadyMemoTasks=附加任务：
WizardPreparing=准备安装
PreparingDesc=正在准备安装 [name]。
CannotContinue=无法继续安装。请点击“取消”退出。
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已安装完成。
FinishedLabel=[name] 已安装完成。您可以通过开始菜单快捷方式启动程序。
ClickFinish=点击“完成”退出安装向导。
RunEntryExec=启动 %1
RunEntryShellExec=查看 %1
StatusExtractFiles=正在复制文件...
StatusCreateIcons=正在创建快捷方式...
StatusCreateIniEntries=正在写入配置...
StatusCreateRegistryEntries=正在写入安装信息...
StatusSavingUninstall=正在保存卸载信息...
StatusRunProgram=正在完成安装...
UninstallStatusLabel=正在卸载 %1，请稍候。
UninstalledAll=%1 已成功卸载。个人设置和配对记录已保留。
ConfirmUninstall=是否卸载 %1 及其程序组件？个人设置和配对记录会保留。
